config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root :to => "home#index"

  post 'sign_in' => "home#sign_in"

  resources :clientes

  resources :solicituds

  resources :servicios

  resources :proveedors

  resources :categoria

end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
	belongs_to :proveedor
	has_many :solicituds
end

app/controllers/servicios_controller.rb
class ServiciosController < ApplicationController
  before_action :set_servicio, only: [:show, :edit, :update, :destroy]

  # GET /servicios
  # GET /servicios.json
  def index
    @servicios = Servicio.all
  end

  # GET /servicios/1
  # GET /servicios/1.json
  def show
  end

  # GET /servicios/new
  def new
    @servicio = Servicio.new
  end

  # GET /servicios/1/edit
  def edit
  end

  # POST /servicios
  # POST /servicios.json
  def create
    @servicio = Servicio.new(servicio_params)

    respond_to do |format|
      if @servicio.save
        format.html { redirect_to @servicio, notice: 'Servicio was successfully created.' }
        format.json { render :show, status: :created, location: @servicio }
      else
        format.html { render :new }
        format.json { render json: @servicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servicios/1
  # PATCH/PUT /servicios/1.json
  def update
    respond_to do |format|
      if @servicio.update(servicio_params)
        format.html { redirect_to @servicio, notice: 'Servicio was successfully updated.' }
        format.json { render :show, status: :ok, location: @servicio }
      else
        format.html { render :edit }
        format.json { render json: @servicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servicios/1
  # DELETE /servicios/1.json
  def destroy
    @servicio.destroy
    respond_to do |format|
      format.html { redirect_to servicios_url, notice: 'Servicio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_servicio
      @servicio = Servicio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def servicio_params
      params.require(:servicio).permit(:descripcion, :proveedor_id)
    end
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/views/servicios/_form.html.erb
<%= form_for(@servicio) do |f| %>
  <% if @servicio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@servicio.errors.count, "error") %> prohibited this servicio from being saved:</h2>

      <ul>
      <% @servicio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% prove = {} %>
  <% Proveedor.all.each do |proveedor| %>
    <% prove[proveedor.nombre] = proveedor.id %>
  <% end %>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :proveedor_id %><br>
    <%= f.select :proveedor_id, prove %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/servicios/edit.html.erb
<h1>Editing servicio</h1>

<%= render 'form' %>

<%= link_to 'Show', @servicio %> |
<%= link_to 'Back', servicios_path %>

app/views/servicios/index.html.erb
<h1>Lista servicios</h1>

<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th>Proveedor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @servicios.each do |servicio| %>
      <tr>
        <td><%= servicio.descripcion %></td>
        <td><%= servicio.proveedor.nombre %></td>
        <td><%= link_to 'Show', servicio %></td>
        <td><%= link_to 'Editar', edit_servicio_path(servicio) %></td>
        <td><%= button_to 'Borrar', servicio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Servicio', new_servicio_path %>
<%= link_to 'Regresar', "categoria" %>

app/views/servicios/new.html.erb
<h1>New servicio</h1>

<%= render 'form' %>

<%= link_to 'Back', servicios_path %>

app/views/servicios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @servicio.descripcion %>
</p>

<p>
  <strong>Proveedor:</strong>
  <%= @servicio.proveedor_id %>
</p>

<%= link_to 'Edit', edit_servicio_path(@servicio) %> |
<%= link_to 'Back', servicios_path %>