config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root :to => "home#index"

  post 'sign_in' => "home#sign_in"

  resources :clientes

  resources :solicituds

  resources :servicios

  resources :proveedors

  resources :categoria

end

app/models/proveedor.rb
class Proveedor < ActiveRecord::Base
	has_many :servicios
	belongs_to :categorium
end

app/controllers/proveedors_controller.rb
class ProveedorsController < ApplicationController
  before_action :set_proveedor, only: [:show, :edit, :update, :destroy]

  # GET /proveedors
  # GET /proveedors.json
  def index
    @proveedors = Proveedor.all
  end

  # GET /proveedors/1
  # GET /proveedors/1.json
  def show
  end

  # GET /proveedors/new
  def new
    @proveedor = Proveedor.new
  end

  # GET /proveedors/1/edit
  def edit
  end

  # POST /proveedors
  # POST /proveedors.json
  def create
    @proveedor = Proveedor.new(proveedor_params)

    respond_to do |format|
      if @proveedor.save
        format.html { redirect_to @proveedor, notice: 'Proveedor was successfully created.' }
        format.json { render :show, status: :created, location: @proveedor }
      else
        format.html { render :new }
        format.json { render json: @proveedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proveedors/1
  # PATCH/PUT /proveedors/1.json
  def update
    respond_to do |format|
      if @proveedor.update(proveedor_params)
        format.html { redirect_to @proveedor, notice: 'Proveedor was successfully updated.' }
        format.json { render :show, status: :ok, location: @proveedor }
      else
        format.html { render :edit }
        format.json { render json: @proveedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proveedors/1
  # DELETE /proveedors/1.json
  def destroy
    @proveedor.destroy
    respond_to do |format|
      format.html { redirect_to proveedors_url, notice: 'Proveedor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proveedor
      @proveedor = Proveedor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proveedor_params
      params.require(:proveedor).permit(:nombre, :email, :direccion, :telefono, :categorium_id)
    end
end

app/helpers/proveedors_helper.rb
module ProveedorsHelper
end

app/views/proveedors/_form.html.erb
<%= form_for(@proveedor) do |f| %>
  <% if @proveedor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proveedor.errors.count, "error") %> prohibited this proveedor from being saved:</h2>

      <ul>
      <% @proveedor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% cats = {}%>
  <%  Categorium.all.each do |cat| %>
    <% cats[cat.nombre] = cat.id %>
  <%  end %>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.text_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :categorium %><br>
    <%= f.select  :categorium_id, cats %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/proveedors/edit.html.erb
<h1>Editing proveedor</h1>

<%= render 'form' %>

<%= link_to 'Show', @proveedor %> |
<%= link_to 'Back', proveedors_path %>

app/views/proveedors/index.html.erb
<% if flash[:notice]  %>
  <span><%= flash[:notice] %></span>
 <% end %>

<h1>Lista de proveedores</h1>

  <thead>
<table>

    <tr>
      <th>Nombre</th>
      <th>Email</th>
      <th>Direccion</th>
      <th>Telefono</th>
      <th>Categoria</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proveedors.each do |proveedor| %>
      <tr>
        <td><%= proveedor.nombre %></td>
        <td><%= proveedor.email %></td>
        <td><%= proveedor.direccion %></td>
        <td><%= proveedor.telefono %></td>
        <td><%= proveedor.categorium.nombre %></td>
        <td><%= link_to 'Ver', proveedor %></td>
        <td><%= link_to 'Editar', edit_proveedor_path(proveedor) %></td>
        <td><%= button_to 'Borrar', proveedor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Proveedor', new_proveedor_path %>

app/views/proveedors/new.html.erb
<h1>New proveedor</h1>

<%= render 'form' %>

<%= link_to 'Back', proveedors_path %>

app/views/proveedors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @proveedor.nombre %>
</p>
<% serv = {} %>
<% @proveedor.servicios.each do |servicio| %>
  <% serv[servicio.descripcion] = servicio.id %>
<% end %>
<% @solicitud = Solicitud.new %>
<%= form_for(@solicitud) do |f| %>
  <% if @solicitud.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@solicitud.errors.count, "error") %> prohibited this solicitud from being saved:</h2>

      <ul>
      <% @solicitud.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="divc">
  <div class="field">
    <%= f.label :servicio_id %><br>
    <%= f.select :servicio_id, serv %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
<% end %>
<%= link_to 'Regresar', "/categoria" %>
<% if session[:user] == 1 %>
<%= link_to 'Servicios', servicios_path %>
<%= link_to 'Solicitudes', "/solicituds" %>
<% end %>