config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root :to => "home#index"

  post 'sign_in' => "home#sign_in"

  resources :clientes

  resources :solicituds

  resources :servicios

  resources :proveedors

  resources :categoria

end

app/models/solicitud.rb
class Solicitud < ActiveRecord::Base
	belongs_to :servicio
	belongs_to :cliente
end

app/controllers/solicituds_controller.rb
class SolicitudsController < ApplicationController
  before_action :set_solicitud, only: [:show, :edit, :update, :destroy]

  # GET /solicituds
  # GET /solicituds.json
  def index
    @solicituds = Solicitud.all
  end

  # GET /solicituds/1
  # GET /solicituds/1.json
  def show
  end

  # GET /solicituds/new
  def new
    @solicitud = Solicitud.new
  end

  # GET /solicituds/1/edit
  def edit
  end

  # POST /solicituds
  # POST /solicituds.json
  def create
    @solicitud = Solicitud.new(servicio_id: params.require(:solicitud).require(:servicio_id), cliente_id: session[:user])

    respond_to do |format|
      if @solicitud.save
        format.html { redirect_to @solicitud, notice: 'Solicitud guardada el proveedor se comunicara con usted.' }
        format.json { render :show, status: :created, location: @solicitud }
      else
        format.html { render :new }
        format.json { render json: @solicitud.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /solicituds/1
  # PATCH/PUT /solicituds/1.json
  def update
    respond_to do |format|
      if @solicitud.update(solicitud_params)
        format.html { redirect_to @solicitud, notice: 'Solicitud was successfully updated.' }
        format.json { render :show, status: :ok, location: @solicitud }
      else
        format.html { render :edit }
        format.json { render json: @solicitud.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /solicituds/1
  # DELETE /solicituds/1.json
  def destroy
    @solicitud.destroy
    respond_to do |format|
      format.html { redirect_to solicituds_url, notice: 'Solicitud was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_solicitud
      @solicitud = Solicitud.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def solicitud_params
      params.require(:solicitud).permit(:servicio_id)
    end
end

app/helpers/solicituds_helper.rb
module SolicitudsHelper
end

app/views/solicituds/_form.html.erb
<%= form_for(@solicitud) do |f| %>
  <% if @solicitud.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@solicitud.errors.count, "error") %> prohibited this solicitud from being saved:</h2>

      <ul>
      <% @solicitud.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% prove = {} %>
  <% Proveedor.all.each do |proveedor| %>
    <% prove[proveedor.nombre] = proveedor.id %>
  <% end %>
  <div class="field">
    <%= f.label :servicio_id %><br>
    <%= f.number_field :servicio_id %>
  </div>
  <div class="field">
    <%= f.label :cliente_id %><br>
    <%= f.number_field :cliente_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/solicituds/edit.html.erb
<h1>Editing solicitud</h1>

<%= render 'form' %>

<%= link_to 'Show', @solicitud %> |
<%= link_to 'Back', solicituds_path %>

app/views/solicituds/index.html.erb
<h1>Lista solicitudes</h1>

<table>
  <thead>
    <tr>
      <th>Servicio</th>
      <th>Cliente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @solicituds.each do |solicitud| %>
      <tr>
        <td><%= solicitud.servicio.descripcion %></td>
        <td><%= solicitud.cliente.nombre %></td>
        <td><%= link_to 'Ver', solicitud %></td>
        <td><%= link_to 'Editar', edit_solicitud_path(solicitud) %></td>
        <td><%= button_to 'Borrar', solicitud, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Solicitud', new_solicitud_path %>

app/views/solicituds/new.html.erb
<h1>New solicitud</h1>

<%= render 'form' %>

<%= link_to 'Back', solicituds_path %>

app/views/solicituds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Servicio:</strong>
  <%= @solicitud.servicio_id %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @solicitud.cliente_id %>
</p>

<%= link_to 'Edit', edit_solicitud_path(@solicitud) %> |
<%= link_to 'Back', solicituds_path %>

<%= link_to 'Regresar', "/categoria" %>